INSERT INTO compliments(content)
VALUES
('You are awesome!'),
('You are amazing!'),
('I hope you have the best day!'),
('You have the best smile!'),
('Nice butt! Have you been working out?'),
('You have impeccable manners!'),
('You have got all the right moves!'),
('Your positivity is infectious!'),
('You are an incredible friend!'),
('Thanks for being you!'),
('Being around you makes everything better!'),
('You are so strong!'),
('You are beautiful inside and out!'),
('Your heart must be 10 times the average size!'),
('You are so down to earth!'),
('You are so unique!'),
('How did you learn to be so great?'),
('Never stop being you!'),
('You continue to impress me!'),
('You''re great at figuring things out'),
('You have a good head on your shoulders'),
('You''re a great example to others'),
('If you were president, you''d be Baberaham Lincoln.'),
('Your potential is limitless!'),
('You''re a smart cookie.'),
('Thank you.'),
('You look great today!'),
('You have great posture.'),
('Your eyes are breathtaking.'),
('You have nice elbows.'),
('You are the most perfect you there is.'),
('On a scale from 1 to 10, you''re an 11.'),
('You are one of a kind'),
('You are really something special'),
('You raise the bar.'),
('You walk the walk.'),
('You have a heart of gold.'),
('There''s ordinary, and then there''s you');
